from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date
from typing import Any, TypeVar

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import ToolMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import StateNode
from pydantic import BaseModel, ValidationError

from stockagent.agents.errors import AgentOutputError, classify_llm_error
from stockagent.agents.facts import (
    apply_fundamentals_facts,
    apply_valuation_facts,
)
from stockagent.agents.fundamentals_agent import build_fundamentals_agent
from stockagent.agents.industry_agent import build_industry_agent
from stockagent.agents.risk_agent import build_risk_agent
from stockagent.agents.state import (
    AnalysisState,
    Evidence,
    FundamentalsOutput,
    IndustryOutput,
    RiskOutput,
    ValuationOutput,
)
from stockagent.agents.subagent_progress import AgentProgressCallbackHandler
from stockagent.agents.valuation_agent import build_valuation_agent
from stockagent.config import LLMConfig
from stockagent.errors import StockAgentError
from stockagent.financials import SecFilingReference
from stockagent.llm import build_model
from stockagent.observability import get_logger
from stockagent.report.citations import render_citations
from stockagent.report.composer import ReportComposer, ReportContent
from stockagent.report.evidence import EvidenceBundle


@dataclass(frozen=True)
class AnalysisNodes:
    """Concrete LangGraph node callables for one stock-analysis workflow."""

    # 调用行业 Agent 并返回 {"industry": IndustryOutput} 的节点
    industry: StateNode
    # 调用基本面 Agent 并返回 {"fundamentals": FundamentalsOutput} 的节点
    fundamentals: StateNode
    # 调用估值 Agent 并返回 {"valuation": ValuationOutput} 的节点
    valuation: StateNode
    # 调用风险 Agent 并返回 {"risk": RiskOutput} 的节点
    risk: StateNode
    # 汇总上游输出并返回 final_report 与 cited_evidence_ids 的节点
    synthesize: StateNode


@dataclass(frozen=True)
class GeneratedReport:
    """Rendered Markdown and the auditable evidence bundle from one analysis run."""

    # 已将内部证据标记渲染为脚注的最终报告正文
    markdown: str
    # 与 markdown 来自同一 final state 的证据、市场输入和 filing 元数据
    evidence_bundle: EvidenceBundle


StructuredOutputT = TypeVar("StructuredOutputT", bound=BaseModel)


class SynthesisOutput(BaseModel):
    """The only two narrative fragments generated by the summary model."""

    # 汇总模型生成的摘要 Markdown 正文，可复用上游内部证据标记
    summary: str
    # 汇总模型生成的投资建议 Markdown 正文，可复用上游内部证据标记
    investment_recommendation: str


def build_analysis_graph(nodes: AnalysisNodes):
    """Build the fixed dependency graph for one report analysis."""
    graph = StateGraph(AnalysisState)
    graph.add_node("industry", nodes.industry)
    graph.add_node("fundamentals", nodes.fundamentals)
    graph.add_node("valuation", nodes.valuation)
    graph.add_node("risk", nodes.risk)
    graph.add_node("synthesize", nodes.synthesize)

    # 从 START 并行运行行业和基本面节点，再依次写入估值、风险和最终报告
    graph.add_edge(START, "industry")
    graph.add_edge(START, "fundamentals")
    graph.add_edge(["industry", "fundamentals"], "valuation")
    graph.add_edge("valuation", "risk")
    graph.add_edge("risk", "synthesize")
    graph.add_edge("synthesize", END)
    return graph.compile()


def build_analysis_nodes(model: BaseChatModel) -> AnalysisNodes:
    """Create the typed node implementations bound to one language model."""
    return AnalysisNodes(
        industry=_build_industry_node(build_industry_agent(model)),
        fundamentals=_build_fundamentals_node(build_fundamentals_agent(model)),
        valuation=_build_valuation_node(build_valuation_agent(model)),
        risk=_build_risk_node(build_risk_agent(model)),
        synthesize=_build_synthesize_node(model),
    )


def _build_industry_node(agent: Any) -> StateNode:
    """Build a node that invokes the industry agent and writes its output to state."""
    def industry(state: AnalysisState) -> dict[str, IndustryOutput]:
        output, _messages = _invoke_structured_agent(
            agent,
            agent_name="industry_analyst",
            payload=_agent_payload(
                "请分析 "
                f"{state['ticker'].upper()} 最近 {state['years']} 个财年的行业趋势、"
                "竞争格局、市场地位和主要挑战。"
            ),
            output_type=IndustryOutput,
        )
        return {"industry": output}

    return industry


def _build_fundamentals_node(agent: Any) -> StateNode:
    """Build a node that invokes the fundamentals agent and writes its output to state."""
    def fundamentals(state: AnalysisState) -> dict[str, FundamentalsOutput]:
        output, messages = _invoke_structured_agent(
            agent,
            agent_name="fundamentals_analyst",
            payload=_agent_payload(
                "请分析 "
                f"{state['ticker'].upper()} 最近 {state['years']} 个财年的盈利能力、"
                "现金流、财务健康和成长性。"
            ),
            output_type=FundamentalsOutput,
        )
        # 编排层只处理 LangChain 消息；工具 JSON 的校验和事实投影由 facts module 负责。
        tool_content = _extract_tool_content(
            messages,
            tool_name="get_fundamentals_analysis",
            agent_name="fundamentals_analyst",
        )
        return {
            "fundamentals": apply_fundamentals_facts(
                output,
                tool_content,
                expected_ticker=state["ticker"],
                expected_years=state["years"],
            )
        }

    return fundamentals


def _build_valuation_node(agent: Any) -> StateNode:
    """Build a node that invokes the valuation agent and writes its output to state."""
    def valuation(state: AnalysisState) -> dict[str, ValuationOutput]:
        output, messages = _invoke_structured_agent(
            agent,
            agent_name="valuation_analyst",
            payload=_agent_payload(
                "请基于以下结构化上游分析评估 "
                f"{state['ticker'].upper()} 最近 {state['years']} 个财年的估值。\n\n"
                f"行业分析：\n{state['industry'].model_dump_json(indent=2)}\n\n"
                f"基本面分析：\n{state['fundamentals'].model_dump_json(indent=2)}"
            ),
            output_type=ValuationOutput,
        )
        # 未经 facts module 覆盖的 LLM 估值字段不得写入 AnalysisState。
        tool_content = _extract_tool_content(
            messages,
            tool_name="compute_valuation_metrics",
            agent_name="valuation_analyst",
        )
        return {
            "valuation": apply_valuation_facts(
                output,
                tool_content,
                expected_ticker=state["ticker"],
                expected_years=state["years"],
            )
        }

    return valuation


def _build_risk_node(agent: Any) -> StateNode:
    """Build a node that invokes the risk agent and writes its output to state."""
    def risk(state: AnalysisState) -> dict[str, RiskOutput]:
        output, _messages = _invoke_structured_agent(
            agent,
            agent_name="risk_analyst",
            payload=_agent_payload(
                "请基于以下结构化上游分析评估 "
                f"{state['ticker'].upper()} 的财务、运营、行业和估值风险。\n\n"
                f"行业分析：\n{state['industry'].model_dump_json(indent=2)}\n\n"
                f"基本面分析：\n{state['fundamentals'].model_dump_json(indent=2)}\n\n"
                f"估值分析：\n{state['valuation'].model_dump_json(indent=2)}"
            ),
            output_type=RiskOutput,
        )
        return {"risk": output}

    return risk


def _build_synthesize_node(model: BaseChatModel) -> StateNode:
    """Build a node that creates summary fragments and composes the final report."""
    def synthesize(state: AnalysisState) -> dict[str, object]:
        logger = get_logger(__name__)
        logger.info("主 agent 开始汇总最终报告")
        response = model.with_structured_output(SynthesisOutput).invoke(
            [
                {
                    "role": "user",
                    "content": (
                        "请只生成摘要和投资建议两个中文 Markdown 正文片段。不要生成整篇"
                        "报告、一级或二级标题、财务表、数据口径、免责声明或参考来源；这些内容"
                        "将由报告编排器固定生成。\n\n"
                        "引用规则：可以复用上游正文已有的内部证据标记，例如 [industry-1]、"
                        "[valuation-1]、[risk-1] 和 [sec-2024]；不得自行发明或改写 URL、"
                        "标题或证据 ID。\n\n"
                        f"行业分析：\n{state['industry'].model_dump_json(indent=2)}\n\n"
                        f"基本面分析：\n{state['fundamentals'].model_dump_json(indent=2)}\n\n"
                        f"估值分析：\n{state['valuation'].model_dump_json(indent=2)}\n\n"
                        f"风险评估：\n{state['risk'].model_dump_json(indent=2)}"
                    ),
                }
            ]
        )
        synthesis = _extract_synthesis_output(response)
        industry = _state_output(state, "industry", IndustryOutput)
        fundamentals = _state_output(state, "fundamentals", FundamentalsOutput)
        valuation = _state_output(state, "valuation", ValuationOutput)
        risk = _state_output(state, "risk", RiskOutput)
        report = ReportComposer().compose(
            ReportContent(
                ticker=state["ticker"],
                report_date=date.today(),
                summary=synthesis.summary,
                industry_analysis=industry.narrative,
                fundamentals_analysis=fundamentals.narrative,
                valuation_analysis=valuation.narrative,
                risk_assessment=risk.narrative,
                investment_recommendation=synthesis.investment_recommendation,
                annual_financials=fundamentals.annual_financials,
                financial_filings=fundamentals.financial_filings,
            )
        )
        # 编排后的全部内部标记一次性替换为 Markdown 脚注
        citation_result = render_citations(
            report,
            _build_evidence_bundle(state, cited_evidence_ids=[]).evidence,
        )
        logger.info("主 agent 完成汇总最终报告")
        return {
            "final_report": citation_result.markdown,
            "cited_evidence_ids": citation_result.cited_evidence_ids,
        }

    return synthesize


def _agent_payload(content: str) -> dict[str, list[dict[str, str]]]:
    return {"messages": [{"role": "user", "content": content}]}


def _invoke_structured_agent(
    agent: Any,
    *,
    agent_name: str,
    payload: dict[str, list[dict[str, str]]],
    output_type: type[StructuredOutputT],
) -> tuple[StructuredOutputT, list[Any]]:
    """Invoke one agent and return its validated local output and local messages."""
    logger = get_logger(__name__)
    logger.info("启动 agent: %s", agent_name)
    result = agent.invoke(
        payload,
        config={"callbacks": [AgentProgressCallbackHandler(agent_name)]},
    )
    output, messages = _extract_structured_response(
        result,
        agent_name=agent_name,
        output_type=output_type,
    )
    logger.info("agent %s 完成", agent_name)
    return output, messages


def _extract_structured_response(
    result: object,
    *,
    agent_name: str,
    output_type: type[StructuredOutputT],
) -> tuple[StructuredOutputT, list[Any]]:
    """Validate an agent's local result and fail before invalid data reaches another node."""
    if not isinstance(result, Mapping):
        raise AgentOutputError(f"{agent_name} returned an invalid result")

    messages = result.get("messages")
    if not isinstance(messages, list):
        raise AgentOutputError(f"{agent_name} result is missing local messages")

    # 扫描本节点消息；任一 ToolMessage 标记为 error 时立即抛出 AgentOutputError
    for message in messages:
        if isinstance(message, ToolMessage) and message.status == "error":
            tool_name = message.name or "unknown tool"
            raise AgentOutputError(f"{agent_name} tool {tool_name} failed: {message.content}")

    response = result.get("structured_response")
    if response is None:
        raise AgentOutputError(f"{agent_name} result is missing structured_response")

    try:
        output = output_type.model_validate(response)
    except ValidationError as exc:
        raise AgentOutputError(
            f"{agent_name} returned an invalid structured_response"
        ) from exc

    return output, messages


def _extract_tool_content(
    messages: list[Any],
    *,
    tool_name: str,
    agent_name: str,
) -> str:
    """Return the latest successful text result for one tool."""
    # Agent 可修正后再次调用同一工具，最后一次成功结果才是当前权威输入。
    tool_message = next(
        (
            message
            for message in reversed(messages)
            if isinstance(message, ToolMessage)
            and message.name == tool_name
            and message.status == "success"
        ),
        None,
    )
    if tool_message is None:
        raise AgentOutputError(f"{agent_name} did not call {tool_name}")
    if not isinstance(tool_message.content, str):
        raise AgentOutputError(f"{tool_name} returned non-text JSON")
    return tool_message.content


def _extract_synthesis_output(response: object) -> SynthesisOutput:
    """Validate the summary model response before it reaches the report composer."""
    try:
        output = SynthesisOutput.model_validate(response)
    except ValidationError as exc:
        raise AgentOutputError("synthesize returned an invalid structured response") from exc

    if not output.summary.strip() or not output.investment_recommendation.strip():
        raise AgentOutputError("synthesize returned an empty structured response")
    return output


def run_stock_analysis_agent(
    ticker: str,
    years: int,
    llm_config: LLMConfig,
) -> GeneratedReport:
    """Run the graph and return a nonempty report with its matched evidence bundle."""
    model = build_model(llm_config)
    graph = build_analysis_graph(build_analysis_nodes(model))
    try:
        result = graph.invoke({"ticker": ticker, "years": years})
    except StockAgentError:
        raise
    except Exception as exc:
        raise classify_llm_error(exc, llm_config.model) from exc

    if not isinstance(result, Mapping):
        raise AgentOutputError("analysis graph returned an invalid final state")
    report = result.get("final_report")
    if not isinstance(report, str) or not report.strip():
        raise AgentOutputError("analysis graph result is missing final_report")
    return GeneratedReport(
        markdown=report,
        evidence_bundle=_build_evidence_bundle(
            result,
            cited_evidence_ids=_extract_cited_evidence_ids(result),
        ),
    )


def _build_evidence_bundle(
    state: Mapping[str, object],
    *,
    cited_evidence_ids: list[str],
) -> EvidenceBundle:
    """Collect all selected evidence and deterministic inputs from the final graph state."""
    industry = _state_output(state, "industry", IndustryOutput)
    fundamentals = _state_output(state, "fundamentals", FundamentalsOutput)
    valuation = _state_output(state, "valuation", ValuationOutput)
    risk = _state_output(state, "risk", RiskOutput)
    # 合并三个 Agent 的网页 evidence 与基本面工具返回的年度 filing evidence
    evidence = [
        *industry.evidence,
        *valuation.evidence,
        *risk.evidence,
        *[_filing_evidence(filing) for filing in fundamentals.financial_filings],
    ]
    return EvidenceBundle(
        evidence=evidence,
        cited_evidence_ids=cited_evidence_ids,
        market_inputs=valuation.market_inputs,
        financial_filings=fundamentals.financial_filings,
    )


def _state_output(
    state: Mapping[str, object],
    name: str,
    output_type: type[StructuredOutputT],
) -> StructuredOutputT:
    """Return a typed required state output or fail at the graph boundary."""
    output = state.get(name)
    if not isinstance(output, output_type):
        raise AgentOutputError(f"analysis graph result is missing {name}")
    return output


def _extract_cited_evidence_ids(state: Mapping[str, object]) -> list[str]:
    """Return the final citation IDs only when the synthesize node produced them."""
    evidence_ids = state.get("cited_evidence_ids")
    if not isinstance(evidence_ids, list) or not all(
        isinstance(evidence_id, str) for evidence_id in evidence_ids
    ):
        raise AgentOutputError("analysis graph result is missing cited_evidence_ids")
    return evidence_ids


def _filing_evidence(filing: SecFilingReference) -> Evidence:
    """Represent one deterministic annual filing as report evidence."""
    return Evidence(
        id=f"sec-{filing.fiscal_year}",
        kind="sec_filing",
        title=(
            f"SEC {filing.form}｜截至 {filing.period_end.isoformat()}｜"
            f"Filed {filing.filed_at.isoformat()}"
        ),
        url=filing.url,
        publisher="SEC",
        published_date=filing.filed_at,
        source_agent="fundamentals_analyst",
    )
